name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: nelsonjcheng/snk-smooth@v1
        with:
          username: Induranga-kawishwara
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/
          git commit -m "Update contribution snake"
          git push
