name: Generate Contribution Snake

on:
  schedule:
    - cron: "30 23 * * *"  # Runs daily at 23:30 UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: jstrieb/github-contribution-snake@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commitMessage: "Update contribution snake"
          version: "v3"

      - name: Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update contribution snake"
          git push
