name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVGs
        run: |
          mkdir -p assets
          # Generate snake.svg (replace with your actual generation code)
          echo '<svg width="100" height="100"><rect width="100" height="100" style="fill:blue"/></svg>' > assets/snake.svg
          # Generate snake-dark.svg (replace with your actual generation code)
          echo '<svg width="100" height="100"><rect width="100" height="100" style="fill:black"/></svg>' > assets/snake-dark.svg

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push
