name: Generate Contribution Snake

on:
  schedule:
    - cron: "30 23 * * *"  # Runs daily at 23:30 UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create necessary directories
        run: mkdir -p generated

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v2
        with:
          github_user_name: "Induranga-kawishwara"  # Your exact username
          outputs: |
            generated/snake.svg
            generated/snake-dark.svg?palette=github-dark

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add generated
          git commit -m "Update contribution snake"
          git push
